## nginx configuration
## Ref: https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md
##
prometheus:
  create: "true"
controller:
  config:
    entries:
      enable-vts-status: "true"
      # proxy-buffer-size: 16k
      server-tokens: "false"
      ssl-redirect: "false"
      worker-connections: "128"
      log-format-escaping: "json"
      log-format: '{"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr",
        "x-forward-for": "$proxy_add_x_forwarded_for", "request_id": "$request_id", "remote_user":
        "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status":$status,
        "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query":
        "$args", "request_length": $request_length, "duration": $request_time,"method":
        "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent"}'

metrics:
  scanInterval: 10s
  port: web
